# Generated by Django 3.0.5 on 2020-09-22 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars')),
                ('description', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, upload_to='backgrounds')),
                ('address', models.CharField(max_length=30)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('wifi', models.CharField(max_length=20)),
                ('facility', models.TextField(blank=True)),
                ('recycle', models.TextField(blank=True)),
                ('house_rule', models.TextField(blank=True)),
                ('content', tinymce.models.HTMLField(default='')),
                ('slug', models.SlugField(default='')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Accommodation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='TouristAttractions')),
                ('caption', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('attraction_phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Attraction', to='accommodations.Accommodation')),
            ],
        ),
    ]
